name: Android Build

on:
  push:
    branches:
      - main  # یا هر شاخه‌ای که تغییرات در آن ثبت می‌شود
  pull_request:
    branches:
      - main  # یا هر شاخه‌ای که تغییرات در آن ثبت می‌شود

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-action@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: true

      - name: Build the APK
        run: ./gradlew assembleRelease  # برای ساخت نسخه release استفاده می‌شود، می‌توانید از assembleDebug برای نسخه debug استفاده کنید.

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/release/*.apk  # مسیر فایل APK ساخته شده
